### ISSUE TITLE
Broken with gtk 3.24.17

### ISSUE THREAD

**Issue by myfreeweb** [wmww/gtk-layer-shell#34] opened 2020-04-04 15:08 UTC
With 3.24.16, everything is fine. With 3.24.17, something is going wrong — in the demo, I can't stretch it by selecting two opposite sides, the buttons don't even become pressed..

**Comment by wmww** [comment] 2020-04-05 06:41
Thanks for bringing this to my attention. It does indeed appear that Wayland resize logic was part of [the changes in this release](https://github.com/GNOME/gtk/compare/3.24.16...3.24.17). I do not yet know how big of a problem this will cause.

**Comment by wmww** [comment] 2020-04-05 07:13
I had trouble building 3.24.17 on Ubuntu due to dependency issues I didn't feel like resolving, but upon switching to Arch I was able to reproduce. I *may* have to trick GTK into thinking it got a configure event, which would involve even more extensive unstable GTK internal hacking than I already do. Hopefully I can find a better way.

**Comment by wmww** [comment] 2020-04-05 09:16
Definitely a GTK bug. I think this will effect anyone who uses GTK custom surfaces on windows that can be resized. Once I got GTK building fixing it inside GTK was extremely easy and the change *should* be non-controversial. Will link the GTK PR once I make it.

**Comment by wmww** [comment] 2020-04-05 09:33
GTK merge request submitted: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1633

**Comment by wmww** [comment] 2020-04-07 13:28
My GTK fix has landed. Now we just have to wait for another release

**Closed by wmww** 2020-04-07 13:28 UTC
