### ISSUE TITLE
missing release and build questions/issues.

### ISSUE THREAD

**Issue by raveit65** [wmww/gtk-layer-shell#4] opened 2019-06-21 09:46 UTC
Any chance of getting a release?
Than i can start a review request for adding it to fedora.

**Comment by raveit65** [comment] 2019-06-21 09:58
Running `make distcheck` to create a tarball gives me this error.
```
Making all in protocol
make[3]: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-dist/gtk-layer-shell-0.1.0/_build/sub/src/protocol'
make[3]: *** No rule to make target 'wlr-layer-shell-unstable-v1.xml', needed by 'wlr-layer-shell-unstable-v1-client.h'.  Stop.
make[3]: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-dist/gtk-layer-shell-0.1.0/_build/sub/src/protocol'
make[2]: *** [Makefile:542: all-recursive] Error 1
```

**Comment by raveit65** [comment] 2019-06-21 10:31
/usr/lib64/libgtk-layer-shell.a

Do i need this file?
Normaly i have to remove all static .a/.la files when building a RPM package.

**Comment by raveit65** [comment] 2019-06-21 10:51
And i get only one build warning
```
gtk-layer-demo.c: In function 'on_orientation_changed':
gtk-layer-demo.c:215:5: warning: 'orient_sub' may be used uninitialized in this function [-Wmaybe-uninitialized]
  215 |     gtk_orientable_set_orientation (GTK_ORIENTABLE (data->first_box), orient_sub);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gtk-layer-demo.c:214:5: warning: 'orient_toplevel' may be used uninitialized in this function [-Wmaybe-uninitialized]
  214 |     gtk_orientable_set_orientation (GTK_ORIENTABLE (data->toplevel_box), orient_toplevel);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by raveit65** [comment] 2019-06-21 11:12
configure gives me this warnings
```
configure.ac:3: installing './missing'
demo/Makefile.am: installing './depcomp'
/usr/share/automake-1.16/am/library.am: warning: 'libgtk-layer-shell.a': linking libraries using a non-POSIX
/usr/share/automake-1.16/am/library.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
src/Makefile.am:2:   while processing library 'libgtk-layer-shell.a'
src/protocol/Makefile.am:17: warning: user target 'clean' defined here ...
automake: ... overrides Automake target 'clean' defined here
src/protocol/Makefile.am:17: consider using clean-local instead of clean
autoreconf: Leaving directory `.'
```

When building with mock (local version of fedora build-server i get those warnings:
```
layer-surface.c: In function 'layer_surface_set_margin':
layer-surface.c:368:41: warning: comparison between 'GtkLayerShellEdge' {aka 'enum <anonymous>'} and 'enum <anonymous>' [-Wenum-compare]
  368 |     g_return_if_fail (edge >= 0 && edge < GTK_LAYER_SHELL_LAYER_ENTRY_NUMBER);
      |                                         ^
/usr/include/glib-2.0/glib/gmacros.h:446:8: note: in definition of macro '_G_BOOLEAN_EXPR'
  446 |    if (expr)                                    \
      |        ^~~~
/usr/include/glib-2.0/glib/gmessages.h:586:9: note: in expansion of macro 'G_LIKELY'
  586 |     if (G_LIKELY (expr)) \
      |         ^~~~~~~~
layer-surface.c:368:5: note: in expansion of macro 'g_return_if_fail'
  368 |     g_return_if_fail (edge >= 0 && edge < GTK_LAYER_SHELL_LAYER_ENTRY_NUMBER);
      |     ^~~~~~~~~~~~~~~~
xdg-toplevel-surface.c:61:43: warning: 'xdg_toplevel_listener' defined but not used [-Wunused-const-variable=]
   61 | static const struct xdg_toplevel_listener xdg_toplevel_listener = {
      |                                           ^~~~~~~~~~~~~~~~~~~~~

```

**Comment by wmww** [comment] 2019-06-21 17:45
* I don't know anything about making releases or packaging *real* software (I've mostly worked on things that don't make it into distros or are managed by someone else), so forgive me for figuring this out as I go along
* I don't know what's up with the `*** No rule to make target 'wlr-layer-shell-unstable-v1.xml'` error. If you understand what `make distcheck` is doing different than `make`, perhaps you have an idea. The src/protocol/Makefile.am is not complicated.
* for simplicity, I was just statically linking gtk-layer-shell. Does it *have* to be dynamically linked and shipped in its own package? The library is small enough that I don't think bloat is too much of an issue.
* You caught 3 bugs. I've now fixed them:
  * Uninitialized orientations: 2cfd80ecadf381aa4dcdb1fcab366eb5ce36e4dc
  * Using the wrong enum: 06e8b1728570cc66cd21323842e0ca37dbebc394
  * Not using toplevel listener: 4b0c0cb62da6736f80874093c34205117737fb48

**Comment by raveit65** [comment] 2019-06-21 18:47
> I don't know what's up with the *** No rule to make target 'wlr-layer-shell-unstable-v1.xml' error. If you understand what make distcheck is doing different than make, perhaps you have an idea. The src/protocol/Makefile.am is not complicated.

` make dist` creates only a tarball from source --> gtk-layer-shell-0.1.0.tar.gz

`make distcheck` does several things:
1. creates the tarball --> gtk-layer-shell-0.1.0.tar.gz
2. extract the tarball to gtk-layer-shell-0.1.0/
3. test building in gtk-layer-shell-0.1.0/_build/sub/
4. test making install in gtk-layer-shell-0.1.0/_inst/
5. test making uninstall from gtk-layer-shell-0.1.0/_inst/

So, i think  that the created tarball with `make dist` or point 1. doesn't have all needed files to execute point 3. successfully.

Well, in my test for PRs i created the tarball will tar.... command, which is working for building a RPM.
So, if you tag a release than github will create a .zip and tar.gz automatic, but without generated make files.
Here an example to creating valid tags.
```
git tag -a v1.5.3 -m 'version 1.5.3'
git show v1.5.3
git push origin v1.5.3
```

`./autogen.sh && make && make distcheck` creates tarballs with generated make files + doing some minimal CI checks.

**Comment by wmww** [comment] 2019-06-22 23:55
I've spent the last day tweaking how popups are handled in an attempt to cover all cases. I *think* it works now, but I need more testing to be sure. Then I can start thinking about releasing again.

**Comment by raveit65** [comment] 2019-07-12 13:01
git from 2019-07-12
ninja gives me a lot of build warnings.
```
[rave@mother gtk-layer-shell-0.1.1]$ ninja -C build
ninja: Entering directory `build'
[2/28] Generating 'src/25a6634@@gtk-layer-shell@sha/wlr-layer-shell-unstable-v1.c'.
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
[4/28] Generating 'src/25a6634@@gtk-layer-shell@sha/xdg-shell.c'.
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
[8/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/gdk-window-hack.c.o'.
In file included from ../src/gtk-wayland.h:7,
                 from ../src/gdk-window-hack.c:2:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../src/gtk-wayland.h:4,
                 from ../src/gdk-window-hack.c:2:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
../src/gdk-window-hack.c: In function 'gdk_window_hack_get_transient_for':
../src/gdk-window-hack.c:22:47: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
   22 |     void **transient_for = (void *)gdk_window + sizeof(GObject) + 2 * sizeof(void *);
      |                                               ^
../src/gdk-window-hack.c:22:65: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
   22 |     void **transient_for = (void *)gdk_window + sizeof(GObject) + 2 * sizeof(void *);
      |                                                                 ^
../src/gdk-window-hack.c: In function 'gdk_window_hack_init':
../src/gdk-window-hack.c:81:59: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
   81 |     void *gdk_window_impl = *(void **)((void *)gdk_window + sizeof(GObject));
      |                                                           ^
../src/gdk-window-hack.c:87:71: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
   87 |     MoveToRectFunc *move_to_rect_func_ptr_ptr = gdk_window_impl_class + sizeof(GObjectClass) + 10 * sizeof(void *);
      |                                                                       ^
../src/gdk-window-hack.c:87:94: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
   87 |     MoveToRectFunc *move_to_rect_func_ptr_ptr = gdk_window_impl_class + sizeof(GObjectClass) + 10 * sizeof(void *);
      |                                                                                              ^
[13/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/gtk-layer-shell.c.o'.
In file included from ../src/gtk-wayland.h:7,
                 from ../src/gtk-layer-shell.c:2:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../include/gtk-layer-shell.h:4,
                 from ../src/gtk-layer-shell.c:1:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
In file included from ../src/gtk-layer-shell.c:6:
../src/xdg-toplevel-surface.h:6:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    6 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from ../src/gtk-wayland.h:7,
                 from ../src/gtk-layer-shell.c:2:
../src/xdg-popup-surface.h:7:27: note: previous declaration of 'GtkWidget' was here
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
[14/28] Compiling C object 'demo/2a97516@@gtk-layer-demo@exe/gtk-layer-demo.c.o'.
../demo/gtk-layer-demo.c:27:21: warning: ISO C forbids initialization between function pointer and 'void *' [-Wpedantic]
   27 |         .arg_data = &layer_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:27:21: note: (near initialization for 'options[0].arg_data')
../demo/gtk-layer-demo.c:36:21: warning: ISO C forbids initialization between function pointer and 'void *' [-Wpedantic]
   36 |         .arg_data = &anchor_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:36:21: note: (near initialization for 'options[1].arg_data')
../demo/gtk-layer-demo.c:45:21: warning: ISO C forbids initialization between function pointer and 'void *' [-Wpedantic]
   45 |         .arg_data = &margin_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:45:21: note: (near initialization for 'options[2].arg_data')
[15/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/custom-shell-surface.c.o'.
In file included from ../src/gtk-wayland.h:7,
                 from ../src/custom-shell-surface.c:2:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../src/custom-shell-surface.h:4,
                 from ../src/custom-shell-surface.c:1:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
[19/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/xdg-toplevel-surface.c.o'.
In file included from ../src/xdg-toplevel-surface.c:1:
../src/xdg-toplevel-surface.h:6:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    6 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../src/custom-shell-surface.h:4,
                 from ../src/xdg-toplevel-surface.h:4,
                 from ../src/xdg-toplevel-surface.c:1:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
In file included from ../src/gtk-wayland.h:7,
                 from ../src/xdg-toplevel-surface.c:4:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from ../src/xdg-toplevel-surface.c:1:
../src/xdg-toplevel-surface.h:6:27: note: previous declaration of 'GtkWidget' was here
    6 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
[20/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/layer-surface.c.o'.
In file included from ../src/gtk-wayland.h:7,
                 from ../src/layer-surface.c:6:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../src/custom-shell-surface.h:4,
                 from ../src/layer-surface.h:4,
                 from ../src/layer-surface.c:1:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
[21/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/gtk-wayland.c.o'.
In file included from ../src/gtk-wayland.h:7,
                 from ../src/gtk-wayland.c:1:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../src/gtk-wayland.h:4,
                 from ../src/gtk-wayland.c:1:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
[22/28] Compiling C object 'src/25a6634@@gtk-layer-shell@sha/xdg-popup-surface.c.o'.
In file included from ../src/xdg-popup-surface.c:1:
../src/xdg-popup-surface.h:7:27: warning: redefinition of typedef 'GtkWidget' [-Wpedantic]
    7 | typedef struct _GtkWidget GtkWidget;
      |                           ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkwidget.h:35,
                 from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../src/custom-shell-surface.h:4,
                 from ../src/xdg-popup-surface.h:4,
                 from ../src/xdg-popup-surface.c:1:
/usr/include/gtk-3.0/gtk/gtktypes.h:46:40: note: previous declaration of 'GtkWidget' was here
   46 | typedef struct _GtkWidget              GtkWidget;
      |                                        ^~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:62,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../src/custom-shell-surface.h:4,
                 from ../src/xdg-popup-surface.h:4,
                 from ../src/xdg-popup-surface.c:1:
../src/xdg-popup-surface.c: In function 'xdg_popup_surface_get_anchor_rect':
../src/xdg-popup-surface.c:106:20: warning: format '%p' expects argument of type 'void *', but argument 4 has type 'GdkWindow *' {aka 'struct _GdkWindow *'} [-Wformat=]
  106 |         g_warning ("Could not find position of child window %p relative to parent window %p",
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  107 |                    self->position.transient_for_gdk_window,
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  GdkWindow * {aka struct _GdkWindow *}
/usr/include/glib-2.0/glib/gmessages.h:339:32: note: in definition of macro 'g_warning'
  339 |                                __VA_ARGS__)
      |                                ^~~~~~~~~~~
../src/xdg-popup-surface.c:106:62: note: format string is defined here
  106 |         g_warning ("Could not find position of child window %p relative to parent window %p",
      |                                                             ~^
      |                                                              |
      |                                                              void *
In file included from /usr/include/glib-2.0/glib.h:62,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../src/custom-shell-surface.h:4,
                 from ../src/xdg-popup-surface.h:4,
                 from ../src/xdg-popup-surface.c:1:
../src/xdg-popup-surface.c:106:20: warning: format '%p' expects argument of type 'void *', but argument 5 has type 'GdkWindow *' {aka 'struct _GdkWindow *'} [-Wformat=]
  106 |         g_warning ("Could not find position of child window %p relative to parent window %p",
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  107 |                    self->position.transient_for_gdk_window,
  108 |                    transient_for_window);
      |                    ~~~~~~~~~~~~~~~~~~~~
      |                    |
      |                    GdkWindow * {aka struct _GdkWindow *}
/usr/include/glib-2.0/glib/gmessages.h:339:32: note: in definition of macro 'g_warning'
  339 |                                __VA_ARGS__)
      |                                ^~~~~~~~~~~
../src/xdg-popup-surface.c:106:91: note: format string is defined here
  106 |         g_warning ("Could not find position of child window %p relative to parent window %p",
      |                                                                                          ~^
      |                                                                                           |
      |                                                                                           void *
```

**Comment by wmww** [comment] 2019-07-12 15:46
Ah yes, I hadn't tested with clang. Will fix

**Comment by wmww** [comment] 2019-07-12 16:26
Clang warnings fixed in 6981ebef8192b9a052a9101ea4a0a25a6c8f90e5

**Comment by raveit65** [comment] 2019-07-12 20:04
Thanks, much better than before. Only the `ISO C` warnings are left.

**Comment by wmww** [comment] 2019-07-12 20:12
*sigh* what? how do I reproduce? I have clang 8.0.1

**Comment by raveit65** [comment] 2019-07-12 20:21
I see them during normal build in f30
```
[rave@mother gtk-layer-shell-0.1.1]$ meson build
The Meson build system
Version: 0.50.1
Source dir: /media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-0.1.1
Build dir: /media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-0.1.1/build
Build type: native build
Project name: gtk-layer-shell
Project version: 0.1.1
Native C compiler: cc (gcc 9.1.1 "cc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.1)
Dependency gtk+-wayland-3.0 found: YES 3.24.10
Dependency wayland-client found: YES 1.17.0
Dependency wayland-scanner found: YES 1.17.0
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Build targets in project: 5
Found ninja-1.9.0 at /usr/bin/ninja


[rave@mother gtk-layer-shell-0.1.1]$ ninja -C build     
ninja: Entering directory `build'
[1/28] Generating 'src/25a6634@@gtk-layer-shell@sha/wlr-layer-shell-unstable-v1.c'.
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
[4/28] Generating 'src/25a6634@@gtk-layer-shell@sha/xdg-shell.c'.
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
[15/28] Compiling C object 'demo/2a97516@@gtk-layer-demo@exe/gtk-layer-demo.c.o'.
../demo/gtk-layer-demo.c:27:21: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   27 |         .arg_data = (void *)&layer_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:36:21: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   36 |         .arg_data = (void *)&anchor_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:45:21: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   45 |         .arg_data = (void *)&margin_option_callback,
      |                     ^
[27/28] Generating GtkLayerShell-0.1.gir with a custom command.
g-ir-scanner: link: cc -o /media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-0.1.1/build/tmp-introspect6k1cgnok/GtkLayerShell-0.1 /media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-0.1.1/build/tmp-introspect6k1cgnok/GtkLayerShell-0.1.o -L. -Wl,-rpath,. -Wl,--no-as-needed -L/media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-0.1.1/build/src -Wl,-rpath,/media/Data-2/Programme/Linux/Mate-Desktop/git-version/others/gtk-layer-shell-0.1.1/build/src -lgtk-layer-shell -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lwayland-client -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -pthread -lgmodule-2.0 -lglib-2.0
[28/28] Generating GtkLayerShell-0.1.typelib with a custom command.
```

**Comment by ddevault** [comment] 2019-08-20 08:40
Relatedly, I would like to see a `meson_options.txt` added which lets us disable/enable demos explicitly, and I would avoid installing demos by default.

**Comment by tristan957** [comment] 2019-08-23 14:39
As a partial GTK/GLib dev myself, I recommend not building with -pedantic as much as you might want to. You'll continuously run into issues like this unless you want to use the preprocessor to ignore certain warnings for certain lines.

**Comment by wmww** [comment] 2019-08-25 20:53
Much of the early discussion here is outdated since the switch to meson, and the later comments are straying further and further off topic. I've created new issues as appropriate. If there's something I missed please create an issue for it.

**Closed by wmww** 2019-08-25 20:53 UTC
