### ISSUE TITLE
Popups misplaced if opened from popover

### ISSUE THREAD

**Issue by AdrianVovk** [wmww/gtk-layer-shell#6] opened 2019-07-04 16:49 UTC
If a popup is opened on top of a popover, it is placed in the center of the screen

To reproduce: Run gtk-layer-demo, place it somewhere, press "Set margin", and right click on one of the entries. The menu will open in the center of the screen.

Here's a video of it happening:
https://streamable.com/dpqo5

**Comment by ammen99** [comment] 2019-07-04 18:01
As the compositor in question is Wayfire, I want to say that this is definitely a bug in gtk-layer-shell, since what we see in the animation means that the popup is interpreted as a `xdg-toplevel` (`xdg-popups` don't have map animations as the one in the video)

**Comment by AdrianVovk** [comment] 2019-07-04 18:56
It also happens in rootston

**Comment by wmww** [comment] 2019-07-04 18:57
Confirmed to happen in Mir as well. Thanks for reporting. Will look into eventually, but not currently my top priority.

**Comment by wmww** [comment] 2019-07-07 05:58
Fixed in e650751826345a1adf4b9484ed238ad18f59c82f

**Closed by wmww** 2019-07-07 05:58 UTC
