### ISSUE TITLE
Input region support

### ISSUE THREAD

**Issue by valpackett** [wmww/gtk-layer-shell#30] opened 2019-09-14 21:33 UTC
Using `input_shape_combine_region` does not work with custom surfaces because `gdk_wayland_window_sync_input_region` is called from `gdk_window_impl_wayland_end_paint` after a `GDK_WINDOW_IS_MAPPED` check, which is only for surfaces mapped through gtk's default xdg shell implementation.

Would be nice if that function just worked, but everything in gdkwindow-wayland is `static` `static` `static`, even the impl class is defined in the `.c` file, so I guess it'd have to be a special API in the layer shell.

(There's also the similar opaque region.)

**Comment by wmww** [comment] 2020-07-07 03:33
Huh, I do not remember seeing this notification, but I would not intentionally have left it without responding. Unfortunately (assuming your analysis is correct), there might not be much I can do. Is this still causing problems for any downstream projects? Is it worth investing any time into looking for a workaround/solution for?

**Comment by myfreeweb** [comment] 2020-07-07 11:30
I personally am not using gtk anymore for layer-shell projects, so maybe not worth it unless someone else asks for it.

> there might not be much I can do

I mean, you couldn't integrate into gtk's API, but you could add a custom API for setting the input region..

**Comment by wmww** [comment] 2020-08-12 20:13
Now that I have gtk-priv, I probably *could* integrate into GTK's API and make it Just Work™, however as far as I know no one is effected by this and I don't even have an easy way to reproduce it. If anyone cares enough, make a PR that exposes this bug in the demo and I'll look into it. Until then, this issue will probably remain open but dormant.

**Comment by dkondor** [comment] 2020-08-16 11:07
Hi,

I might have a use-case that is affected by this: docks in cairo-dock that set a custom input shape. Basically, cairo-dock works mostly nicely as a layer-shell surface, but monitoring input focus seems to be buggy, sometimes the dock becomes stuck after the mouse leaves it. See also the discussion here:
https://github.com/Cairo-Dock/cairo-dock-core/pull/8

I haven't had much time to investigate this, but it is using gtk_widget_input_shape_combine_region() to set a custom shape for the dock.

Let me know what you think. I'm happy to try to look into this more.
Thanks!

**Comment by wmww** [comment] 2020-08-16 20:47
As I said on the other thread just now, I probably wont have time to look seriously at this for over a week. If this goes away on Wayland-without-layer-shell, then that would be an indicator that problem is indeed caused by this bug.

**Comment by dkondor** [comment] 2020-08-17 06:45
Hi,
I've tested and it seems the problem is present even without layer shell, so the issue is probably elsewhere. I'll try to investigate and see if it can be fixed without layer shell first.

**Comment by dkondor** [comment] 2020-08-19 04:42
Hi,
I've looked into the issue with cairo-dock more, and it turns out the real cause was code relying on global pointer position. With a workaround for that, now the code setting the custom input shape actually seems to be working well, even with layer-shell (and GDK 3.22). So I'm not sure if this issue still exists, at least my use case does not seem to be affected by it :)

**Closed** 2023-02-27 19:07 UTC
Labels: enhancement

**Comment by wmww** [comment] 2023-02-27 19:18
C code to demonstrate that it works:
```c
cairo_rectangle_int_t rect = {
    50, 50, 100, 100
};
cairo_region_t *region = cairo_region_create_rectangle (&rect);
gtk_widget_input_shape_combine_region(GTK_WIDGET (initial_window), region);
cairo_region_destroy (region);
```

or Python:
```python
import cairo
region = cairo.Region(cairo.RectangleInt(50, 50, 100, 100))
window.input_shape_combine_region(region)
```
