### ISSUE TITLE
[Question] How to position custom child window?

### ISSUE THREAD

**Issue by dkondor** [wmww/gtk-layer-shell#59] opened 2020-08-16 11:02 UTC
Hi,
thanks for developing gtk-layer-shell!

I have a question regarding its usage where I'm not sure if I understand things correctly. I'm wanting to create a custom child GtkWindow of a layer-shell surface that can be positioned relative to it, similarly to menus and popups, but with more flexibility regarding content. The main use case is that I'm exploring how to make cairo-dock (https://glx-dock.org/) work on Wayland compositors with the layer-shell protocol (https://github.com/dkondor/cairo-dock-core/tree/layer_shell). Here, subdocks are GtkWindows that need to be positioned relative to their main dock.

I've found that gdk_window_move_to_rect() is the recommended (/only?) way to position a child window relative to a parent. But the only way I could make this work with gtk-layer-shell surfaces seems to me more like a hack. Basically, if I call gtk_layer_init_for_window() for the child window, then positioning does not seem to work at all. On the other hand, it can be made to work if a gdk_window_move_to_rect() is added at the right time, specifically when the window is realized. So basically, I have to connect to the window's realize signal and call gdk_window_move_to_rect() from there; this results in the new window becoming a layer-shell surface that is positioned properly relative to its parent.

I feel like I'm missing something; or is this use-case not supported yet?

I have created a minimal example (by modifying the demo) here:
https://github.com/dkondor/gtk-layer-shell/blob/demo_popup/demo/popup-window.c
It adds a button to the demo window, that creates a custom popup that is positioned relative to some arbitrary location in the parent. This only works if the gdk_window_move_to_rect() call is made in the window_realize_cb() callback.

Note: I'm still using GDK 3.22 (on Ubuntu 18.04), so I need to ugly hack included to access gdk_window_move_to_rect() (adapted from gtk-priv-access.c).

Any thoughts on this are appreciated!

**Comment by wmww** [comment] 2020-08-16 20:32
Hi, first of all I have minimal time today and for the next week, so I probably wont be able to build your demo/add features within that time frame (as I normally would), but I think just explaining how things work on the Wayland end would be helpful.

I *think* you're trying to do something that works on X but not on Wayland in general. To test this hypothesis, remove calls to GTK Layer Shell entirely. The Cairo window should  still work, it will just be a floating window instead of anchored to a screen edge. Popups and popovers should work the same as they do when using with GTK Layer Shell. If things aren't right then either, then the issue is with how you're using GTK on Wayland (NOT a bug/missing feature in GTK Layer Shell). I'm happy to help you resolve this problem, but it's out-of-scope of what this library attempts to fix automatically.

The reason I don't think this is a Layer Shell-specific bug is that Layer Shell surfaces can not be children. If you want a window to be positioned relative to a parent you should not be calling `gtk_layer_init_for_window()` on it at all. You might be able to "fake" a parent-child relationship by using large margins to position the "child" where it should end up, but this method is complicated, error-prone and should only be used as a last resort.

Better options are to make this window a "popover" (what GTK calls subsurfaces) or popup. GTK Layer Shell automatically detects when a popup's parent is a layer shell surface, and does all the necessary hacks to make that work. You should never call `gtk_layer_init_for_window()` on a popup or subsurfaces. Note that the popup/popover approach *should* also work on X11. If you don't loose any functionality in the rafactor, you might end up just using the new code for both platforms instead of maintaining both ways of doing it.

# Background
This might help you understand why things are the way they are. GTK can only do what the Wayland protocols it uses allow, and that's somewhat more limited than on X11.

## XDG toplevels
In Wayland, an XDG shell toplevel surface is the equivalentt of a normal X11 window (XDG shell is a wayland protocol extension that is supported by almost all clients/servers). X11 windows can be positioned by the client, but XDG shell surfaces can not. It's positioning is entirely dependent on the server's implementation. The client can't even find out where the compositor decided to put the window. This goes for "child" windows as well (such as file save dialogs), but NOT for popups and subsurfaces.

## XDG shell popups
The client can give the server rules for how to position popups (ie try to put it here but flip it around if that would cause the popup to go off the screen). Remember, the client doesn't know where its surfaces are, so it can't make those decisions itself. In GTK, right-click menus and tooltips are both implemented as popups.

## Subsurfaces
All Wayland surfaces can have subsurfaces (including subsurfaces themselves). I believe subsurfaces are called "popovers" or something in GTK. Subsurfaces can extend beyond their parent surface, but are considered as part of it. They always have an exact location given by the client. If you shrink a Gedit window, move it next to the edge of the screen and open the hamburger menu, the menu will extend off the edge of the screen. This is because it's implemented with a subsurface instead of a popup.

## Layer shell surfaces
Toplevels don't allow for positioning and popups and subsurfaces only allow positioning relative to a parent, so Layer shell (an alternative protocol to XDG shell) is needed in order to implement dock/notification/wallpaper/etc type functionality. Layer shell surfaces can also have subsurfaces and popups (you can make an XDG popup off of a layer shell surface, which is only a little confusing.

**Comment by wmww** [comment] 2020-08-16 20:40
NOTE: Sway currently has a problem with subsurfaces on Layer Shell popups, but these things usually get fixed in a timely manor: https://github.com/swaywm/sway/issues/5617

**Closed** 2020-09-16 23:15 UTC
